# Generated by Django 6.0.6 on 2026-06-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название валюты')),
                ('char_code', models.CharField(max_length=3, unique=True, verbose_name='Буквенный код (USD)')),
                ('num_code', models.CharField(max_length=3, verbose_name='Цифровой код')),
                ('nominal', models.IntegerField(default=1, verbose_name='Номинал')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Целевой курс')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на курс',
                'verbose_name_plural': 'Подписки на курсы',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, max_length=10, verbose_name='Курс к рублю')),
                ('date_checked', models.DateField(verbose_name='Дата фиксации курса')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'История курсов',
                'unique_together': {('currency', 'date_checked')},
            },
        ),
    ]
